package com.pawlife;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*;

@RestController
@RequestMapping("/api")
@CrossOrigin(origins = "*")
public class PetController {

    @GetMapping({"/pets", "/pets/"})
    public ResponseEntity<?> getAllPets(@RequestParam(value = "search", required = false) String search) {
        try {
            StringBuilder sql = new StringBuilder(
                "SELECT p.pet_id, p.pet_name, p.species, p.breed, p.date_of_birth, p.gender, p.microchip_no, p.photo_url, " +
                "u.first_name || ' ' || u.last_name AS owner_name, u.phone_number AS owner_phone " +
                "FROM pets p " +
                "LEFT JOIN pet_owners po ON p.owner_id = po.owner_id " +
                "LEFT JOIN users u ON po.user_id = u.user_id " +
                "WHERE 1=1 "
            );

            List<Object> params = new ArrayList<>();
            if (search != null && !search.trim().isEmpty()) {
                sql.append("AND (LOWER(p.pet_name) LIKE ? OR LOWER(p.microchip_no) LIKE ? OR LOWER(u.first_name) LIKE ? OR LOWER(u.last_name) LIKE ?) ");
                String term = "%" + search.trim().toLowerCase() + "%";
                params.add(term); params.add(term); params.add(term); params.add(term);
            }
            sql.append("ORDER BY p.pet_id DESC");

            List<Map<String, Object>> pets = Database.query(sql.toString(), params.toArray());
            return ResponseEntity.ok(Map.of("success", true, "pets", pets));
        } catch (Exception e) {
            return ResponseEntity.internalServerError().body(Map.of("success", false, "error", e.toString()));
        }
    }

    @GetMapping("/pets/{id}")
    public ResponseEntity<?> getPetDetails(@PathVariable("id") long id) {
        try {
            Map<String, Object> pet = Database.getFirst(
                "SELECT p.*, po.emergency_contact, " +
                "u.first_name, u.last_name, u.phone_number, u.email " +
                "FROM pets p " +
                "LEFT JOIN pet_owners po ON p.owner_id = po.owner_id " +
                "LEFT JOIN users u ON po.user_id = u.user_id " +
                "WHERE p.pet_id = ?", id
            );
            if (pet == null) {
                return ResponseEntity.status(404).body(Map.of("success", false, "error", "Pet not found"));
            }

            List<Map<String, Object>> consults = Database.query(
                "SELECT c.*, p.medication_details, p.dosage, p.instructions " +
                "FROM consultations c LEFT JOIN prescriptions p ON c.consultation_id = p.consultation_id " +
                "WHERE c.pet_id = ? ORDER BY c.consultation_date DESC", id
            );
            List<Map<String, Object>> vaccines = Database.query(
                "SELECT * FROM vaccination_records WHERE pet_id = ? ORDER BY date_administered DESC", id
            );

            return ResponseEntity.ok(Map.of("success", true, "pet", pet, "consultations", consults, "vaccinations", vaccines));
        } catch (Exception e) {
            return ResponseEntity.internalServerError().body(Map.of("success", false, "error", e.toString()));
        }
    }

    @PostMapping({"/pets", "/pets/"})
    public ResponseEntity<?> registerPet(@RequestBody Map<String, Object> body) {
        try {
            String name = (String) body.get("pet_name");
            String species = (String) body.getOrDefault("species", "Dog");
            String breed = (String) body.getOrDefault("breed", "Mixed Breed");
            String dob = (String) body.getOrDefault("date_of_birth", LocalDate.now().minusYears(1).toString());
            String gender = (String) body.getOrDefault("gender", "Male");
            String chip = (String) body.get("microchip_no");
            String allergies = (String) body.getOrDefault("allergies", "None");

            if (name == null || name.trim().isEmpty()) {
                return ResponseEntity.badRequest().body(Map.of("success", false, "error", "Pet name is a mandatory field."));
            }

            boolean isAutoGeneratedChip = false;
            if (chip == null || chip.trim().isEmpty()) {
                chip = "MC-" + (int)(100000 + Math.random() * 900000);
                isAutoGeneratedChip = true;
            }

            long ownerId = 1; 
            String ownerPhone = (String) body.get("owner_phone");
            String ownerEmail = (String) body.get("owner_email");
            
            if ((ownerPhone != null && !ownerPhone.trim().isEmpty()) || (ownerEmail != null && !ownerEmail.trim().isEmpty())) {
                String ownerFname = (String) body.get("owner_fname");
                String ownerLname = (String) body.get("owner_lname");
                String ownerName = (String) body.get("owner_name");
                if ((ownerFname == null || ownerFname.trim().isEmpty()) && ownerName != null && !ownerName.trim().isEmpty()) {
                    String[] parts = ownerName.trim().split("\\s+", 2);
                    ownerFname = parts[0];
                    ownerLname = parts.length > 1 ? parts[1] : "Client";
                }
                if (ownerFname == null || ownerFname.trim().isEmpty()) ownerFname = "Registered";
                if (ownerLname == null || ownerLname.trim().isEmpty()) ownerLname = "Client";
                String ownerPassword = (String) body.getOrDefault("owner_password", "password123");
                
                if (ownerPhone == null) ownerPhone = "";
                if (ownerEmail == null || ownerEmail.trim().isEmpty()) ownerEmail = "client." + System.currentTimeMillis() + "@pawlife.lk";

                try {
                    long newUserId = Database.executeInsert(
                        "INSERT INTO users (first_name, last_name, email, password, phone_number, role, status) VALUES (?, ?, ?, ?, ?, 'Pet Owner', 'Active')",
                        ownerFname, ownerLname, ownerEmail, ownerPassword, ownerPhone
                    );
                    ownerId = Database.executeInsert("INSERT INTO pet_owners (user_id, emergency_contact) VALUES (?, ?)", newUserId, ownerPhone);
                } catch (Exception e) {
                    if (e.toString() != null && e.toString().contains("UNIQUE constraint failed")) {
                        ownerEmail = "client." + System.currentTimeMillis() + "@pawlife.lk";
                        long newUserId = Database.executeInsert(
                            "INSERT INTO users (first_name, last_name, email, password, phone_number, role, status) VALUES (?, ?, ?, ?, ?, 'Pet Owner', 'Active')",
                            ownerFname, ownerLname, ownerEmail, ownerPassword, ownerPhone
                        );
                        ownerId = Database.executeInsert("INSERT INTO pet_owners (user_id, emergency_contact) VALUES (?, ?)", newUserId, ownerPhone);
                    } else {
                        throw e;
                    }
                }
            } else if (body.get("owner_id") != null) {
                ownerId = HttpUtils.toLong(body.get("owner_id"), 1L);
            }

            long id = -1;
            int retries = 5;
            while (retries > 0) {
                try {
                    id = Database.executeInsert(
                        "INSERT INTO pets (owner_id, pet_name, species, breed, date_of_birth, gender, microchip_no, allergies) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                        ownerId, name.trim(), species.trim(), breed.trim(), dob.trim(), gender.trim(), chip.trim(), allergies.trim()
                    );
                    break;
                } catch (Exception e) {
                    if (e.toString() != null && (e.toString().contains("microchip_no") || e.toString().contains("Duplicate"))) {
                        if (isAutoGeneratedChip && retries > 1) {
                            chip = "MC-" + (int)(100000 + Math.random() * 900000);
                            retries--;
                            continue;
                        } else {
                            return ResponseEntity.badRequest().body(Map.of("success", false, "error", "The microchip number '" + chip.trim() + "' is already registered to another pet."));
                        }
                    }
                    throw e;
                }
            }

            Database.logAudit(2, "De Silva L.P.B (Veterinary EHR)", "PET_REGISTRATION", "Pet EHR", "Registered new pet: " + name + " [ID: " + id + "]");

            return ResponseEntity.ok(Map.of("success", true, "pet_id", id, "message", "Pet '" + name + "' registered successfully with Microchip " + chip + "."));
        } catch (Exception e) {
            return ResponseEntity.internalServerError().body(Map.of("success", false, "error", e.toString()));
        }
    }

    @DeleteMapping("/pets/{id}")
    public ResponseEntity<?> deletePet(@PathVariable("id") long id) {
        try {
            int rows = Database.executeUpdate("DELETE FROM pets WHERE pet_id = ?", id);
            if (rows > 0) {
                Database.logAudit(1, "Sanvidu S.D.N (Admin)", "PET_DELETED", "Pet EHR", "Deleted pet profile with ID: " + id);
                return ResponseEntity.ok(Map.of("success", true, "message", "Pet profile deleted successfully."));
            } else {
                return ResponseEntity.status(404).body(Map.of("success", false, "error", "Pet not found."));
            }
        } catch (Exception e) {
            return ResponseEntity.internalServerError().body(Map.of("success", false, "error", e.toString()));
        }
    }

    @PostMapping({"/consultations", "/pets/consultations"})
    public ResponseEntity<?> createConsultation(@RequestBody Map<String, Object> body) {
        try {
            long petId = HttpUtils.toLong(body.get("pet_id"), 0L);
            String diagnosis = (String) body.get("diagnosis");
            String notes = (String) body.getOrDefault("treatment_notes", "");
            String symptoms = (String) body.getOrDefault("symptoms", "Clinical examination");
            String vitals = (String) body.getOrDefault("vitals", "Normal");
            String meds = (String) body.get("medication_details");
            String dosage = (String) body.get("dosage");
            String instructions = (String) body.get("instructions");

            if (diagnosis == null || diagnosis.trim().isEmpty()) {
                return ResponseEntity.badRequest().body(Map.of("success", false, "error", "Clinical Error: Diagnosis is a mandatory clinical field."));
            }

            long consultId = Database.executeInsert(
                "INSERT INTO consultations (appointment_id, pet_id, vet_id, symptoms, vitals, diagnosis, treatment_notes) VALUES (1, ?, 2, ?, ?, ?, ?)",
                petId, symptoms, vitals, diagnosis, notes
            );

            if (meds != null && !meds.trim().isEmpty()) {
                Database.executeInsert(
                    "INSERT INTO prescriptions (consultation_id, pet_id, vet_id, medication_details, dosage, instructions, status) VALUES (?, ?, 2, ?, ?, ?, 'Active')",
                    consultId, petId, meds, dosage != null ? dosage : "As directed", instructions != null ? instructions : "Take with food"
                );
            }

            Database.logAudit(2, "De Silva L.P.B (Veterinary EHR)", "CLINICAL_CONSULTATION", "Pet EHR", "Logged consultation for Pet ID " + petId + ". Diagnosis: " + diagnosis);

            return ResponseEntity.ok(Map.of("success", true, "consultation_id", consultId, "message", "Clinical consultation record and digital prescription saved."));
        } catch (Exception e) {
            return ResponseEntity.internalServerError().body(Map.of("success", false, "error", e.toString()));
        }
    }

    @PostMapping({"/vaccinations", "/pets/vaccinations"})
    public ResponseEntity<?> createVaccination(@RequestBody Map<String, Object> body) {
        try {
            long petId = HttpUtils.toLong(body.get("pet_id"), 0L);
            String vaccineName = (String) body.get("vaccine_name");
            String batchNumber = (String) body.get("batch_number");
            String adminDate = (String) body.get("date_administered");

            if (vaccineName == null || batchNumber == null || adminDate == null) {
                return ResponseEntity.badRequest().body(Map.of("success", false, "error", "Vaccine name, batch number, and administration date are required."));
            }

            LocalDate nextDueDate = LocalDate.parse(adminDate).plusYears(1);
            String nextDueStr = nextDueDate.format(DateTimeFormatter.ISO_LOCAL_DATE);
            String certNo = "CERT-VAC-" + (int)(1000 + Math.random() * 9000);

            long recId = Database.executeInsert(
                "INSERT INTO vaccination_records (pet_id, vaccine_name, batch_number, date_administered, next_due_date, certificate_no, administered_by, status, remarks) VALUES (?, ?, ?, ?, ?, ?, 2, 'Completed', 'Administered during clinic visit.')",
                petId, vaccineName, batchNumber, adminDate, nextDueStr, certNo
            );

            Database.logAudit(2, "De Silva L.P.B (Veterinary EHR)", "VACCINATION_RECORDED", "Pet EHR", "Recorded vaccination: " + vaccineName + " for Pet ID " + petId);

            return ResponseEntity.ok(Map.of(
                "success", true, "record_id", recId, "next_due_date", nextDueStr, "certificate_no", certNo, 
                "message", "Vaccination record logged successfully. Next preventative due date calculated: " + nextDueStr
            ));
        } catch (Exception e) {
            return ResponseEntity.internalServerError().body(Map.of("success", false, "error", e.toString()));
        }
    }
}
